# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cq < Formula
  desc "CLI tool to check AI provider quota usage"
  homepage "https://github.com/jacobcxdev/cq"
  version "0.21.7"
  license "MIT"

  depends_on "python@3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.21.7/cq_0.21.7_darwin_amd64.tar.gz"
      sha256 "76e46b9e5d04c414a627df948c4f5049dfbcc25df22a01c93e1717ff2817bb05"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.21.7/cq_0.21.7_darwin_arm64.tar.gz"
      sha256 "01b6cee84e856df71304b39c188725b031edae2de981f802ac4a24c21ab886c9"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.21.7/cq_0.21.7_linux_amd64.tar.gz"
      sha256 "bd4cd65483c5efd850e9afd77d165b707fdd80ed7127cf92dd5fa89d714ffec8"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.21.7/cq_0.21.7_linux_arm64.tar.gz"
      sha256 "678bc82c8dcda71a50cb786085af460f9d75848bf6c2581fbe429d5ebc8c5a64"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  def post_install
    system Formula["python@3"].opt_bin/"python3", "-m", "pip", "install", "--break-system-packages", "--quiet", "headroom-ai[all]"
  end

  service do
    run [opt_bin/"cq", "proxy", "start"]
    keep_alive true
    log_path File.expand_path("~/Library/Logs/cq/proxy.log")
    error_log_path File.expand_path("~/Library/Logs/cq/proxy.log")
    working_dir Dir.home
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
