# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cq < Formula
  desc "CLI tool to check AI provider quota usage"
  homepage "https://github.com/jacobcxdev/cq"
  version "0.13.1"
  license "MIT"

  depends_on "python@3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.13.1/cq_0.13.1_darwin_amd64.tar.gz"
      sha256 "223bc085f4d11e5a62388f5a9237dec24df17cfa3e7246838a45c726f43a874d"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.13.1/cq_0.13.1_darwin_arm64.tar.gz"
      sha256 "469765672737447c2c8c548d661b829765593bb15fb80fa7387e5470c27a9466"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.13.1/cq_0.13.1_linux_amd64.tar.gz"
      sha256 "9f4006af696476b679b15dc73c101e9e7192310e68c384a375d511825c200237"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobcxdev/cq/releases/download/v0.13.1/cq_0.13.1_linux_arm64.tar.gz"
      sha256 "8a7205bcc36ee08384d34f7558293b43ba48c5a3e6f17c788c1f0fa7faac5a1e"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  def post_install
    system Formula["python@3"].opt_bin/"python3", "-m", "pip", "install", "--break-system-packages", "--quiet", "headroom-ai[all]"
  end

  service do
    run [opt_bin/"cq", "proxy", "start"]
    keep_alive true
    log_path File.expand_path("~/Library/Logs/cq/proxy.log")
    error_log_path File.expand_path("~/Library/Logs/cq/proxy.log")
    working_dir Dir.home
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
