# typed: strict
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "cq" do
  version "0.29.12"

  on_macos do
    on_arm do
      sha256 "5038675dfd6f57c9adf6a3cde7aeabcdbd8f186fae1bbd916822ab20ab1b3c71"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b054751eab6bda0e34d7d752be4f5d700aa930a87dc058e334abef1b32ffb7d"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "876d2e7d74724500e68cffd076f3cfd804ac91858bcbe7c9a3357f4dc1a20362"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b104202ecd2fba923ee760bd75f9292c3a6459db444d968be788a0d35cd2247"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cq"
  desc "CLI tool to check AI provider quota usage"
  homepage "https://github.com/jacobcxdev/cq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cq"

  postflight do
    if OS.mac?
      attributes = system_command "/usr/bin/xattr",
                                  args:         ["#{HOMEBREW_PREFIX}/bin/cq"],
                                  print_stdout: false
      if attributes.stdout.lines(chomp: true).include?("com.apple.quarantine")
        system_command "/usr/bin/xattr",
                       args: ["-d", "com.apple.quarantine", "#{HOMEBREW_PREFIX}/bin/cq"]
      end
      remaining_attributes = system_command "/usr/bin/xattr",
                                            args:         ["#{HOMEBREW_PREFIX}/bin/cq"],
                                            print_stdout: false
      if remaining_attributes.stdout.lines(chomp: true).include?("com.apple.quarantine")
        raise "cq remains quarantined after installation"
      end
    end
    system_command "#{HOMEBREW_PREFIX}/bin/cq",
                   args: [
                     "service", "install", "--owner=homebrew",
                     "--service-executable=#{HOMEBREW_PREFIX}/bin/cq"
                   ]
  end

  uninstall_preflight do
    if File.executable?("#{HOMEBREW_PREFIX}/bin/cq")
      system_command "#{HOMEBREW_PREFIX}/bin/cq",
                     args: [
                       "service", "uninstall", "--owner=homebrew",
                       "--service-executable=#{HOMEBREW_PREFIX}/bin/cq"
                     ]
    end
    system_command "/bin/launchctl",
                   args:         ["bootout", "gui/#{Process.uid}/dev.jacobcx.cq.proxy"],
                   must_succeed: false
    system_command "/bin/launchctl",
                   args:         ["bootout", "gui/#{Process.uid}/dev.jacobcx.cq.refresh"],
                   must_succeed: false
    system_command "/bin/rm",
                   args: ["-f", "#{Dir.home}/Library/LaunchAgents/dev.jacobcx.cq.proxy.plist"]
    system_command "/bin/rm",
                   args: ["-f", "#{Dir.home}/Library/LaunchAgents/dev.jacobcx.cq.refresh.plist"]
  end

  # No zap stanza required
end
