# typed: strict
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "cq" do
  version "0.31.6"

  on_macos do
    on_arm do
      sha256 "3dede7c17fd58bebb182af547590e44e6e4ea69bb3d065a5dd71f77c75cef2f8"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31266b11f09dfaf8ac593e885043a54a954c038ae0c3268466e0ae0162b3e999"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae23743e60e163afd7c052ba7c35aaefe14fc02c1cb1aeed594b2cddb3769689"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "431e6f2ec3c1482a0084882dba08f277a3d1d2afc77978409d25961436937a3a"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cq"
  desc "CLI tool to check AI provider quota usage"
  homepage "https://github.com/jacobcxdev/cq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cq"

  postflight do
    if OS.mac?
      attributes = system_command "/usr/bin/xattr",
                                  args:         ["#{HOMEBREW_PREFIX}/bin/cq"],
                                  print_stdout: false
      if attributes.stdout.lines(chomp: true).include?("com.apple.quarantine")
        system_command "/usr/bin/xattr",
                       args: ["-d", "com.apple.quarantine", "#{HOMEBREW_PREFIX}/bin/cq"]
      end
      remaining_attributes = system_command "/usr/bin/xattr",
                                            args:         ["#{HOMEBREW_PREFIX}/bin/cq"],
                                            print_stdout: false
      if remaining_attributes.stdout.lines(chomp: true).include?("com.apple.quarantine")
        raise "cq remains quarantined after installation"
      end
    end
    system_command "#{HOMEBREW_PREFIX}/bin/cq",
                   args: [
                     "service", "install", "--owner=homebrew",
                     "--service-executable=#{HOMEBREW_PREFIX}/bin/cq"
                   ]
  end

  uninstall_preflight do
    if File.executable?("#{HOMEBREW_PREFIX}/bin/cq")
      system_command "#{HOMEBREW_PREFIX}/bin/cq",
                     args: [
                       "service", "uninstall", "--owner=homebrew",
                       "--service-executable=#{HOMEBREW_PREFIX}/bin/cq"
                     ]
    end
    system_command "/bin/launchctl",
                   args:         ["bootout", "gui/#{Process.uid}/dev.jacobcx.cq.proxy"],
                   must_succeed: false
    system_command "/bin/launchctl",
                   args:         ["bootout", "gui/#{Process.uid}/dev.jacobcx.cq.refresh"],
                   must_succeed: false
    system_command "/bin/rm",
                   args: ["-f", "#{Dir.home}/Library/LaunchAgents/dev.jacobcx.cq.proxy.plist"]
    system_command "/bin/rm",
                   args: ["-f", "#{Dir.home}/Library/LaunchAgents/dev.jacobcx.cq.refresh.plist"]
  end

  # No zap stanza required
end
