# This file was generated by GoReleaser. DO NOT EDIT.
cask "cq" do
  cq_lifecycle_script = <<~'SH'
    #!/bin/bash
    set -euo pipefail
    action=$1
    source=$2
    target=$3
    if [[ "$action" == install ]]; then
      attributes=$(/usr/bin/xattr "$source")
      if grep -Fxq com.apple.quarantine <<<"$attributes"; then
        /usr/bin/xattr -d com.apple.quarantine "$source"
      fi
      attributes=$(/usr/bin/xattr "$source")
      if grep -Fxq com.apple.quarantine <<<"$attributes"; then
        echo "cq remains quarantined after installation" >&2
        exit 1
      fi
      linked=0
      if [[ -e "$target" || -L "$target" ]]; then
        if [[ ! -L "$target" || ! "$target" -ef "$source" ]]; then
          echo "refusing to replace existing CQ executable: $target" >&2
          exit 1
        fi
      else
        /bin/ln -s "$source" "$target"
        linked=1
      fi
      if ! "$source" service install --owner=homebrew "--service-executable=$target"; then
        if [[ "$linked" == 1 && -L "$target" && "$target" -ef "$source" ]]; then
          /bin/rm "$target"
        fi
        exit 1
      fi
    elif [[ "$action" == uninstall ]]; then
      if [[ -x "$source" && "$target" -ef "$source" ]]; then
        "$source" service uninstall --owner=homebrew "--service-executable=$target"
      elif [[ -e "$target" || -L "$target" ]]; then
        if [[ ! -L "$target" || "$(readlink "$target")" != "$source" ]]; then
          echo "refusing to uninstall a different CQ executable: $target" >&2
          exit 1
        fi
      fi
      /bin/launchctl bootout "gui/$UID/dev.jacobcx.cq.proxy" >/dev/null 2>&1 || true
      /bin/launchctl bootout "gui/$UID/dev.jacobcx.cq.refresh" >/dev/null 2>&1 || true
      /bin/rm -f "$HOME/Library/LaunchAgents/dev.jacobcx.cq.proxy.plist" \
                 "$HOME/Library/LaunchAgents/dev.jacobcx.cq.refresh.plist"
    else
      echo "unknown Homebrew lifecycle action: $action" >&2
      exit 64
    fi
  SH
  version "0.33.7"

  on_macos do
    on_arm do
      sha256 "9f07bf372811c99013b15beeb4c97fbf921b07cb5e7fc3783d80b1a67732e463"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc3c1f75e9b349b1f9ebf3405d6c39083ff5b600d5ae7d4ce682a4c712efcaa8"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "603c1e2d1f77f5b03638955480da40335690e5324f4fc75ff644286ca8b44ee0"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ced95cc533625702ec59b6829c7963b4e526c040ab749cab42a65aa34f18832c"
      url "https://github.com/jacobcxdev/cq/releases/download/v#{version}/cq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cq"
  desc "CLI tool to check AI provider quota usage"
  homepage "https://github.com/jacobcxdev/cq"

  livecheck do
    skip "Auto-generated on release."
  end

  installer script: {
    executable: "/bin/bash",
    args:       [
      "-c", cq_lifecycle_script, "cq-homebrew-lifecycle", "install",
      "#{HOMEBREW_CASKROOM}/#{token}/0.33.7/cq", "#{HOMEBREW_PREFIX}/bin/cq"
    ],
  }
  binary "cq"

  uninstall script: {
    executable: "/bin/bash",
    args:       [
      "-c", cq_lifecycle_script, "cq-homebrew-lifecycle", "uninstall",
      "#{HOMEBREW_CASKROOM}/#{token}/0.33.7/cq", "#{HOMEBREW_PREFIX}/bin/cq"
    ],
  }

  # No zap stanza required
end
